import { MovimentacaoEstoque, Venda, Cliente } from "@/types";

export const movimentacoesExemplo: MovimentacaoEstoque[] = [
  {
    id: "1",
    produtoId: "1",
    produtoNome: "Smartphone Samsung Galaxy S24",
    tipo: "entrada",
    quantidade: 10,
    data: new Date("2024-02-01"),
    observacao: "Reposição de estoque",
  },
  {
    id: "2",
    produtoId: "2",
    produtoNome: "Camiseta Polo Básica",
    tipo: "entrada",
    quantidade: 25,
    data: new Date("2024-02-02"),
    observacao: "Nova coleção",
  },
  {
    id: "3",
    produtoId: "1",
    produtoNome: "Smartphone Samsung Galaxy S24",
    tipo: "saida",
    quantidade: 3,
    data: new Date("2024-02-05"),
    observacao: "Venda",
  },
  {
    id: "4",
    produtoId: "3",
    produtoNome: "Cafeteira Elétrica Premium",
    tipo: "entrada",
    quantidade: 5,
    data: new Date("2024-02-08"),
    observacao: "Reposição",
  },
  {
    id: "5",
    produtoId: "2",
    produtoNome: "Camiseta Polo Básica",
    tipo: "saida",
    quantidade: 8,
    data: new Date("2024-02-10"),
    observacao: "Venda",
  },
  {
    id: "6",
    produtoId: "4",
    produtoNome: "Tênis de Corrida Nike",
    tipo: "saida",
    quantidade: 2,
    data: new Date("2024-02-12"),
    observacao: "Venda",
  },
];

// Dados de exemplo para vendas
export const vendasExemplo: Venda[] = [
  {
    id: "v1",
    produtoId: "1",
    produtoNome: "Smartphone Samsung Galaxy S24",
    quantidade: 2,
    precoUnitario: 2500,
    precoTotal: 5000,
    data: new Date(), // Hoje
    cliente: "João Silva",
  },
  {
    id: "v2",
    produtoId: "2",
    produtoNome: "Camiseta Polo Básica",
    quantidade: 3,
    precoUnitario: 89.90,
    precoTotal: 269.70,
    data: new Date(), // Hoje
    cliente: "Maria Santos",
  },
  {
    id: "v3",
    produtoId: "3",
    produtoNome: "Cafeteira Elétrica Premium",
    quantidade: 1,
    precoUnitario: 450,
    precoTotal: 450,
    data: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000), // Ontem
    cliente: "Pedro Costa",
  },
  {
    id: "v4",
    produtoId: "4",
    produtoNome: "Tênis de Corrida Nike",
    quantidade: 1,
    precoUnitario: 320,
    precoTotal: 320,
    data: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000), // 2 dias atrás
    cliente: "Ana Lima",
  },
  {
    id: "v5",
    produtoId: "1",
    produtoNome: "Smartphone Samsung Galaxy S24",
    quantidade: 1,
    precoUnitario: 2500,
    precoTotal: 2500,
    data: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000), // 3 dias atrás
    cliente: "Carlos Oliveira",
  },
  {
    id: "v6",
    produtoId: "2",
    produtoNome: "Camiseta Polo Básica",
    quantidade: 5,
    precoUnitario: 89.90,
    precoTotal: 449.50,
    data: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000), // 5 dias atrás
    cliente: "Lucia Fernandes",
  },
  {
    id: "v7",
    produtoId: "3",
    produtoNome: "Cafeteira Elétrica Premium",
    quantidade: 2,
    precoUnitario: 450,
    precoTotal: 900,
    data: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000), // 8 dias atrás
    cliente: "Roberto Silva",
  },
  {
    id: "v8",
    produtoId: "4",
    produtoNome: "Tênis de Corrida Nike",
    quantidade: 3,
    precoUnitario: 320,
    precoTotal: 960,
    data: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000), // 15 dias atrás
    cliente: "Fernanda Costa",
  },
];

// Dados de exemplo para clientes
export const clientesExemplo: Cliente[] = [
  {
    id: "c1",
    nome: "João Silva",
    email: "joao.silva@email.com",
    telefone: "(11) 99999-9999",
    endereco: "Rua das Flores, 123",
    cidade: "São Paulo",
    estado: "SP",
    cep: "01234-567",
    dataCadastro: new Date("2024-01-15"),
    ativo: true,
  },
  {
    id: "c2",
    nome: "Maria Santos",
    email: "maria.santos@email.com",
    telefone: "(21) 88888-8888",
    endereco: "Av. Copacabana, 456",
    cidade: "Rio de Janeiro",
    estado: "RJ",
    cep: "22071-900",
    dataCadastro: new Date("2024-01-20"),
    ativo: true,
  },
  {
    id: "c3",
    nome: "Pedro Costa",
    email: "pedro.costa@email.com",
    telefone: "(31) 77777-7777",
    endereco: "Rua da Liberdade, 789",
    cidade: "Belo Horizonte",
    estado: "MG",
    cep: "30112-000",
    dataCadastro: new Date("2024-02-01"),
    ativo: true,
  },
  {
    id: "c4",
    nome: "Ana Lima",
    email: "ana.lima@email.com",
    telefone: "(85) 66666-6666",
    endereco: "Rua do Sol, 321",
    cidade: "Fortaleza",
    estado: "CE",
    cep: "60160-230",
    dataCadastro: new Date("2024-02-05"),
    ativo: false,
  },
  {
    id: "c5",
    nome: "Carlos Oliveira",
    email: "carlos.oliveira@email.com",
    telefone: "(47) 55555-5555",
    endereco: "Av. Beira Mar, 654",
    cidade: "Florianópolis",
    estado: "SC",
    cep: "88010-400",
    dataCadastro: new Date("2024-02-10"),
    ativo: true,
  },
];
